### ISSUE TITLE
Valkyria 引擎的文本导回后要怎么让文本显示正常

### ISSUE THREAD

**Issue by singiaoba** [Dir-A/Dir-A_Essays_MD#10]
用DAT_Editor解包回封
用SDT_TextEditor 以cp936回封中文文本
要如何处理程序，让文本正常显示
![ede](https://github.com/user-attachments/assets/cfe72e7e-95ea-47eb-9ff5-d872e05c34ec)

**Comment by Dir-A** [comment]
https://github.com/ZQF-ReVN/RxValkyria/issues/6

**Comment by singiaoba** [comment]
非常的感谢，文本的问题解决了
请问程序窗口标题的乱码要如何解决
![ddd](https://github.com/user-attachments/assets/691cda57-dbb4-45ae-8be5-728d299c183a)

**Comment by Dir-A** [comment]
对应system.dat文件，参照VAL_SysData_Seg_0结构，修改aWindowTitle成员
https://github.com/ZQF-ReVN/RxValkyria/blob/main/etc/note.md
![QQ20240824-233027](https://github.com/user-attachments/assets/89d8031e-e431-40cd-ac66-442c9626b854)
