### ISSUE TITLE
Re-direct file reading help

### ISSUE THREAD

**Issue by mingyue2108** [Dir-A/Dir-A_Essays_MD#12]
Hi sir. I'm trying to create a translation patch for Doukyuusei Remake. The game can read loose files without packing, but that makes the game folder look too messy. I don't want to use Enigma Virtual Box or similar software because it might trigger anti-virus for users.
Can you help me hook the engine to read files from a selected directory, like you did with HorkEyes and CMVS?

[https://www.ryuugames.com/eng-doukyuusei-bangin-summer/](url)

**Comment by Dir-A** [comment]
![QQ_1725461731073](https://github.com/user-attachments/assets/0b4378a8-be95-4d7c-b851-12d90f41756b)
give it a try.
- unzip `x32-Release.zip` and put `doukyuusei_hook.dll` and `doukyuusei_loader.exe` into game directory.
- place the files to be replaced in the FileHook folder.
- execute `doukyuusei_loader.exe`

[x32-Release.zip](https://github.com/user-attachments/files/16872465/x32-Release.zip)
[src.zip](https://github.com/user-attachments/files/16872466/src.zip)

**Comment by mingyue2108** [comment]
It works, thank you so much! If possible, could you change it to dsound proxy and add this RxHook function to modify strings within the executable file?

![image](https://github.com/user-attachments/assets/2c92ba74-4885-4b82-9b23-7386f77cf81f)

Also, could you make it support the Steam version as well? Here is the exe:

[doukyuusei.zip](https://github.com/user-attachments/files/16885977/doukyuusei.zip)

Thanks again!

**Comment by Dir-A** [comment]
I don't have a steam version to test, you'll need to test it by yourself
[release.zip](https://github.com/user-attachments/files/16896749/release.zip)
[src.zip](https://github.com/user-attachments/files/16896750/src.zip)

**Comment by mingyue2108** [comment]
The game doesn't run when using new dll

**Comment by mingyue2108** [comment]
Can't run either

**Comment by Dir-A** [comment]
Then there's nothing I can do. I don't have a steam environment.
