### ISSUE TITLE
我想修改一款Exhibit引擎作品读GBK，应该是用GetGlyphOutlineA函数生成字模；在函数下断成功后，找不到要改的0x80编码，求助

### ISSUE THREAD

**Issue by HathawayLinNoa** [Dir-A/Dir-A_Essays_MD#15]
1_首先是尝试在CreateFontIndirectA函数下断点，在游戏运行后点击start，游戏继续运行，下断失败。
   利用其他工具(Misaka Hook)尝试检查

2_经过Misaka Hook检查，发现GetGlyphOutlineA/ GetTextExtentExPointA/Retouch 三种Hook方法可正常获取内容
![Hook](https://github.com/user-attachments/assets/b880723d-6f11-40be-80ff-fd503473732b)

3_于是尝试在DBG内分别搜索以上三种名称，

其中GetGlyphOutlineA与GetTextExtentExPointA较易下断点，

## Retouch函数在运行前查不到，运行后存在较多Retouch____名称，故忽略。

经测试，在GetGlyphOutlineA与GetTextExtentExPointA函数下断点，游戏在进入Start界面后成功暂停，下断成功。

![DBG0](https://github.com/user-attachments/assets/f332373c-aa0d-48d5-8bd1-19b05365a0c5)

此时堆栈窗口出现结构 
0397F9C4   037BB6B3  /CALL 到 GetTextExtentExPointA 来自 resident.037BB6AD
0397F9C8   E2011F2C  |hDC = E2011F2C
0397F9CC   02B0B170  |Text = "记述"
0397F9D0   00000004  |TextLen = 0x4
0397F9D4   000001F8  |MaxExtent = 1F8 (504.)
0397F9D8   0397FA94  |pMaxChar = 0397FA94
0397F9DC   00000000  |pExtents = NULL
0397F9E0   0397FA78  \pSize = 0397FA78
对CALL 到 GetTextExtentExPointA进行反汇编窗口跟随，

![DBG1](https://github.com/user-attachments/assets/993c7bb6-5dc2-4a43-b00b-e3e5ecdd40bd)

反汇编窗口出现结构
037BB699  |.  51            ||push ecx                               ; /pSize = E2011F2C
037BB69A  |.  6A 00         ||push 0x0                               ; |pExtents = NULL
037BB69C  |.  8D55 60       ||lea edx,[arg.23]                       ; |
037BB69F  |.  52            ||push edx                               ; |pMaxChar = 0397FA94
037BB6A0  |.  50            ||push eax                               ; |MaxExtent = 2B0B170 (45134192.)
037BB6A1  |.  57            ||push edi                               ; |TextLen = 0x4
037BB6A2  |.  8B45 54       ||mov eax,[arg.20]                       ; |
037BB6A5  |.  50            ||push eax                               ; |Text = "记述"
037BB6A6  |.  8B8E A4010000 ||mov ecx,dword ptr ds:[esi+0x1A4]       ; |
037BB6AC  |.  51            ||push ecx                               ; |hDC = E2011F2C
037BB6AD  |.  FF15 2C907E03 ||call dword ptr ds:[<&GDI32.GetTextExte>; \GetTextExtentExPointA

此时  TEXT文本与寄存器内EAX正确为汉化后内容“记叙”   
## 可能是txt内在开头处隐藏了ASC II字段

而结构特别像在给WINDOWS API函数准备参数，
但我实在没有找到lfCharSet或0x80，
通过常数查找，发现多个0x80， 作为计算机小白，经过多轮修改测试依然没有成功，需要大佬求助
图片没有完整展示反汇编代码，虽尝试F7F8步进步过寻找可能是字符编码的位置，但徒劳无功，应该是我水平太低了 

##游戏存在多个DLL，推测联结剧本生成字模的模块为resident.dll
![DLL](https://github.com/user-attachments/assets/667b22c0-8721-434d-850f-5a3caf1ed67b)

**Comment by HathawayLinNoa** [comment]
啊？双#备注在GIT是会放大的？ 抱歉   纯计算机外行

**Comment by HathawayLinNoa** [comment]
游戏名[MOONSTONE] Clear－クリア

**Comment by Dir-A** [comment]
这个游戏调用CreateFontIndirectA的地方主要有三处，
exe两处va:0x00401A0E，va:0x00420F76
resident.dll一处rva:0xA9AB6
文本显示主要在resident.dll中处理，虽然resident.dll只有一处调用，但此处是一个统一的封装接口，即函数rva:A9A10，
其它地方都调用这个函数来调用CreateFontIndirectA，而且有好几处硬编码0x80的位置，位置太多不好找齐全部
![QQ_1733667321804](https://github.com/user-attachments/assets/756766a5-41a4-4ce8-b301-24252e52a200)

最直接的方法是hook CreateFontIndirectA去改，但实际上没必要，因为CreateFontIndirectA已经被封装在函数rva:A9A10中，所有调用CreateFontIndirectA都走函数rva:A9A10，而函数rva:A9A10在栈中的第五个参数就是charset

所以最简单的方法是修改函数rva:A9A10
具体为patch resident.dll: rva:A9A50 
```asm
mov al, 0x86
nop
nop
```
![QQ_1733667003294](https://github.com/user-attachments/assets/affd6a62-e0e0-4880-b568-86d4e9e02331)
![QQ_1733667251579](https://github.com/user-attachments/assets/d7b6ea99-598d-4210-b8c6-98ca55c3cd0e)
![QQ_1733667030230](https://github.com/user-attachments/assets/10c4e8c9-d1e4-4eb3-b6f6-f08c5e34a371)

patch 过的resident.dll
[resident.zip](https://github.com/user-attachments/files/18052594/resident.zip)
