### ISSUE TITLE
[汉化问题] NEKOSDK引擎汉化问题

### ISSUE THREAD

**Issue by adsf0427** [Dir-A/Dir-A_Essays_MD#6]
在尝试汉化游戏 [WAFFLE] 毒舌悪魔とムッツリ天使との四畳半暮らし时，提取脚本并修改游戏文本为中文字符后，使用GBK编码重新注入文本时，游戏显示出现乱码。

步骤：
1. 使用 [engine_nekosdk](https://github.com/mnakamura1337/engine_nekosdk) 提取脚本并修改游戏文本。
2. 将文本的编码设置为GBK。
3. 将修改后的文本重新注入脚本。

实际行为
游戏中文本显示为乱码。

**Comment by Dir-A** [comment]
- 首先使用WinHex查看导入到脚本的编码是否为GBK，不是则请修改成GBK导入
![1](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/05724e45-5d62-4d28-8af7-28b10f43c33e)
- 修改DBCS字符的边界检查（SJIS范围改到GBK范围）
在x32dbg中打开exe，在反汇编窗口右键搜索常量，输入0x9F
![QQ截图20240518124501](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/7b5e8729-4b8f-4564-971e-96e4cfbe9ff8)
![QQ截图20240518124535](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/dcea2215-df1b-4b40-9bc6-2d76aa7bfb3b)
选中cmp 开头的这个结果，双击回到反汇编窗口
其上是一个0x81则该位置正确
![QQ截图20240518124656](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/e691cf2a-a469-4b1d-b02a-26496cc62abc)
选中 cmp al 9F 按下空格，编辑该条汇编指令，将9F修改成FE
![QQ截图20240518124817](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/ce4f447e-801e-4a47-ad33-c8346fad38a2)
![QQ截图20240518124854](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/2c5d9675-012d-4036-a83f-1a480b029adc)

- 修改CreateFontA的charset
两个选择，一是手动修改，二是[使用HookFont自动处理](https://github.com/Dir-A/VN_Localization_Tutorials/tree/main/%E5%85%B6%E5%AE%83/Hook%E5%AD%97%E4%BD%93)
以下演示手动修改
一般来说这个引擎只有一处统一调用CreateFontA，则只需要搜索所有的Intermodular call既可以
依旧是在反汇编窗口右键
![QQ截图20240518125215](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/0c9f2f8e-1197-4ca9-82ac-9b5f7081e151)
输入筛选字符串 `CreateFont` 可以看到唯一结果，双击转到反汇编窗口
![QQ截图20240518125256](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/1c9afba2-b9bc-46ef-80ab-a68eca71f447)
其上有个push 80，与刚刚方法一样，修改成0x86
![QQ截图20240518125404](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/51dfbe8a-b924-451d-b63c-3b49c297ac75)
修改完成过点击菜单栏下方的创可贴图标，表示保存修改的内容，在弹出的对话框中确认修改的内容后保存文件
![QQ截图20240518125618](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/8b00cb85-9166-4e39-882b-d7c6cf346f13)

![QQ截图20240518125916](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/02b664eb-cb90-4b4c-a49f-1a289a069f79)

**Comment by adsf0427** [comment]
感谢，解决了
