### ISSUE TITLE
KR引擎更改编码显示异常

### ISSUE THREAD

**Issue by qtlark** [Dir-A/Dir-A_Essays_MD#7]
### 概要
游戏名：ひこうき雲の向こう側
参考视频：https://www.bilibili.com/video/BV1m64y187df
实现目标：不转区运行本体EXE

### 流程
1. 直接打开原版EXE，显示找不到某某文件的后缀名
![image](https://github.com/Dir-A/Dir-A_Essays_MD/assets/55882882/ac5e4f52-d424-4c27-9bfa-37892822423c)

2. 提取data.xp3，将所有asd, func, tjs, ks, txt, ini, csv (以及stage, stand特有文件后缀)的编码从shift-js转到utf16 LE有签名，并且在Config.tjs里挂载了路径，在Override.tjs里挂载了CSV插件。最后打包成patch.xp3。

3. 运行游戏，正常无报错。台词，人名，语音，BGM，背景图片等等显示正常，但立绘还是显示不出来。但此时转区运行正常。

### 想法
之前反应的黑框问题是乌龙，是忘挂载路径了。但挂载路径后，就出现了上述的③问题，就是黑框都没了，一片透明。个人感觉是加载到了TLG图片，但是显示不了？不懂，迷惑。
![image](https://github.com/Dir-A/Dir-A_Essays_MD/assets/55882882/fa633d27-18b8-4a04-8edf-b73ef06ab715)

**Comment by Dir-A** [comment]
这个游戏封包里非常文件夹杂了日文的文件名，一般这种建议直接走forcedataxp3的方法，因为path.xp3并不能很好的替换，当然想一点点把路径修好也是可以的，只是很麻烦。

目前来说你有两个选择
### 删除立绘控制txt
- 1、所有操作和你上述一样
- 2、把fgimage文件夹下各个人物名文件夹内的txt从patch里删除，比如 fgimage\いろは１\いろは１.txt，这些文件不要放入path了，其它操作一样，就可以正常显示立绘了

### 使用forcedataxp3
21:11
https://www.bilibili.com/video/BV1qQ4y1k7Gs/

**Comment by Dir-A** [comment]
理论上来说无论什么编码，最终都是一串二进制序列，只要没对编码过的数据进行转换，就可以匹配到相应的文件，顶对只是显示出来的内容有问题，内部运行一般是不会有问题的，然而比较糟糕的是Windows下通常不认为字符串是二进制序列，通常会为字符串假定一个编码，比如是sjis编码的，然后通过api把字符串转换成utf16编码，如果假设的编码是错误的，那么转换出来的utf6编码的字符串也是有问题的，有可能少字符有可能全是问号，比如一个文件名，输入是编码是sjis但以gbk来转换，转换到utf16后，就完全是乱码的状态了，根本不可能通过这个文件名找到对应的文件。

反正这东西就这样的，编码混乱，替换混乱，有些插件还不支持某些编码

所以最好是forcedataxp3从最顶级的data目录来替换文件，让所有编码都统一成utf16，就没这个问题了（当然有些傻x的插件没做utf16的bom检查和支持除外）

**Comment by qtlark** [comment]
感谢大佬解释Orz
