### ISSUE TITLE
Shift-jis redirect help

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/Dir-A_Essays_MD#8]
The english release of [this game](https://vndb.org/v3896) doesn't display shift-jis characters:
![image](https://github.com/Dir-A/Dir-A_Essays_MD/assets/81801486/e6168ff1-3729-41dd-a80e-1434f1f3b5fb)
[Link](https://f95zone.to/threads/sisters-last-day-of-summer-jast-usa-jellyfish.210825/)
Also, if possible, can you fix the weird full-width drawing of this game?
I'll attach sample files here.
[data.zip](https://github.com/user-attachments/files/15542267/data.zip)

**Comment by Dir-A** [comment]
![QQ截图20240705220100](https://github.com/Dir-A/Dir-A_Essays_MD/assets/79064817/c03e7fc7-0987-480d-bdcd-0f457a7a8d40)
[Uploading src.zip…]()
[release.zip](https://github.com/user-attachments/files/16110632/release.zip)

**Comment by Dir-A** [comment]
didn't finish analyzing, just found the offset of the encrypted string in the ism file, then decrypted it and modified it

**Comment by Cosetto** [comment]
Ok then

**Comment by Cosetto** [comment]
Hi bro, could you check the game again? Half-width katakana doesn't work.
![image](https://github.com/user-attachments/assets/40700f4e-c46e-4408-a643-ebf38ad7fb3e)
![image](https://github.com/user-attachments/assets/ea679e6e-8213-43af-9e7d-25d41f11e6eb)
![image](https://github.com/user-attachments/assets/4ee08927-e197-4e17-bbd0-a8f31de2c9c5)

**Comment by Cosetto** [comment]
Thanks again bro

**Comment by Cosetto** [comment]
Edited images don't load when packing back. Maybe we can just hook like this https://github.com/Dir-A/Dir-A_Essays_MD/issues/12

**Comment by Cosetto** [comment]
Also, this is the dll from the latest update on steam
[ism.zip](https://github.com/user-attachments/files/16931076/ism.zip)

**Comment by Dir-A** [comment]
didn't have this problem in my environment
please provide the files needed for this problem to occur.

**Comment by Cosetto** [comment]
![image](https://github.com/user-attachments/assets/a20a3e6e-c3e9-4ecc-9296-3b7bee9e8a19)
![image](https://github.com/user-attachments/assets/79b346fb-a94d-4d31-bafb-1405748712fd)

**Comment by Dir-A** [comment]
![QQ_1726029211250](https://github.com/user-attachments/assets/cbb31fe8-e24c-4e43-8238-3fcd4cbc2f83)
It should be 0000, it's some kind of flag, probably related to file lookups

**Comment by Cosetto** [comment]
@Dir-A 
https://github.com/amayra/arc_conv/blob/master/arc_pack/arc_ism.asm
Yikes, it's written in asm

**Comment by Dir-A** [comment]
https://github.com/amayra/arc_conv/blob/master/arc_pack/arc_ism.asm#L33
maybe it's the line.

I don't think you need to change anything, just change 01 to 0 in the repacked file
I'll be posting new tools in the next few days at ReVN.

**Comment by Dir-A** [comment]
https://github.com/Dir-A/ReVN/releases

**Comment by Cosetto** [comment]
Could you take a look for script tool too?

**Comment by Dir-A** [comment]
what script tool？

**Comment by Cosetto** [comment]
Nevermind, I think I could handle ism script somehow. Thanks
Could you check the other issue?
