### ISSUE TITLE
关于tyrano游戏解包后再封包,运行不正常的问题

### ISSUE THREAD

**Issue by 282167361** [Dir-A/Dir-A_Essays_MD#9]
下载了一个tyrano游戏(PC端),游戏本来是可以正常运行的,我想要解包后再封包成apk的在手机上运行,我接下来的方式是:
1.使用asar extract app.asar的方法将app.asar文件解包拿到资源
2.使用tyranoBuilder创建一个新项目,然后将解包的资源覆盖到新项目中
3.使用AndroidStudio利用tyrano官网的安卓框架打包成apk 

现在问题就是游戏运行起来,点击对话框,点着点着发现点不动了,不会进行下一个对话,一开始以为是打包成安卓才有这种问题,后来发现法宝成PC版本也有这个问题,甚至tyranoBuilder直接运行也有这种情况,并且试了几个游戏都是这样.

这种创建一个新游戏然后拿解包出来的资源覆盖过去是我在B站看到的,是否因为这样会导致脚本运行异常导致对话框无法继续点击下去

**Comment by Dir-A** [comment]
版本也不看你就覆盖？
